name: Build and deploy to test environment
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  setup:
    uses: equinor/data-marketplace-adapter-service/.github/workflows/_setup.yml@main
    with:
      cache-key: ${{ github.sha }}
    secrets: inherit

  check-code:
    uses: equinor/data-marketplace-adapter-service/.github/workflows/_checks.yml@main
    needs: setup
    with:
      cache-key: ${{ github.sha }}
    secrets: inherit

  deploy:
    uses: equinor/data-marketplace-adapter-service/.github/workflows/_deploy.yml@main
    needs: [setup, check-code]
    with:
      environment: test
      cache-key: ${{ github.sha }}
    secrets: inherit
