name: Build and deploy to production environment
on:
  workflow_dispatch:

jobs:
  setup:
    uses: equinor/data-marketplace-adapter-service/.github/workflows/_setup.yml@main
    with:
      cache-key: ${{ github.sha }}
    secrets: inherit

  check-code:
    uses: equinor/data-marketplace-adapter-service/.github/workflows/check-code.yml@main
    needs: setup
    with:
      cache-key: ${{ github.sha }}
    secrets: inherit

  deploy:
    uses: equinor/data-marketplace-adapter-service/.github/workflows/_deploy.yml@main
    needs: [setup, check-code]
    with:
      environment: prod
      cache-key: ${{ github.sha }}
    secrets: inherit
