name: Check code
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '**/*.{j,t}s'
  pull_request:
    branches:
      - main
    paths:
      - '**/*.{j,t}s'

jobs:
  setup:
    name: Checkout and setup
    uses: equinor/data-marketplace-adapter-service/.github/workflows/_setup.yml@main
    with:
      cache-key: ${{ github.sha }}
    secrets: inherit
  checks:
    name: Run checks
    uses: equinor/data-marketplace-adapter-service/.github/workflows/_checks.yml@main
    with:
      cache-key: ${{ github.sha }}
    secrets: inherit
